version: "3"

services:
  postgres:
    image: postgres:9.6
    restart: on-failure
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buru_db
    ports:
      - "5432:5432"

  phoenix:
    build:
      context: .
    restart: on-failure
    volumes:
      - ./app:/app:delegated
      - .bash_history:/root/.bash_history
      - deps:/app/deps
      - _build:/app/_build
      - node_modules:/app/assets/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres

volumes:
  deps:
  _build:
  node_modules:
  